/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GerenciarFuncionarios;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Leonardo
 */
public class FuncionarioView extends javax.swing.JPanel {
    private GerenciarFuncionarios FuncionariosListener;
    /**
     * Creates new form FuncionarioView
     */
    public FuncionarioView() {
        initComponents();
        InputFuncionario_Codigo.setVisible(false);
        
        FuncionariosListener = new GerenciarFuncionarios(this);
        botaoFuncionario_Limpar.addActionListener(FuncionariosListener);
        botaoFuncionario_Salvar.addActionListener(FuncionariosListener);
        botaoFuncionario_Pesquisar.addActionListener(FuncionariosListener);
        
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                
                if (me.getClickCount() >= 2 && row!= -1) {
                       FuncionariosListener.setFuncionario_values(row);
                }
            }
        });
    }

    public JTextField getInputFuncionario_Codigo() {
        return InputFuncionario_Codigo;
    }
    
    public JTextField getInputFuncionario_Cpf() {
        return InputFuncionario_Cpf;
    }

    public JTextField getInputFuncionario_Data() {
        return InputFuncionario_Data;
    }

    public JTextField getInputFuncionario_Nome() {
        return InputFuncionario_Nome;
    }

    public JTextField getInputFuncionario_Telefone() {
        return InputFuncionario_Telefone;
    }
    
    public JTextField getInputFuncionario_Cargo() {
        return InputFuncionario_Cargo;
    }
    
    public JNumberFormatField getInputFuncionario_Salario() {
        return InputFuncionario_Salario;
    }
    
    public JTextField getInputFuncionario_Usuario() {
        return InputFuncionario_Usuario;
    }
    
    public JTextField getInputFuncionario_Senha() {
        return InputFuncionario_Senha;
    }

    public JTextField getInputPesquisa_Funcionario() {
        return InputPesquisa_Funcionario;
    }

    public JTable getjTable1() {
        return jTable1;
    }
    
    public JCheckBox getFuncionario_Ativo(){
        return checkFuncionario_Ativo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InputFuncionario_Nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        InputFuncionario_Cpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputFuncionario_Telefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        InputFuncionario_Cargo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        InputFuncionario_Data = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        InputFuncionario_Usuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        InputFuncionario_Senha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        botaoFuncionario_Limpar = new javax.swing.JButton();
        botaoFuncionario_Salvar = new javax.swing.JButton();
        InputFuncionario_Codigo = new javax.swing.JTextField();
        InputFuncionario_Salario = new view.JNumberFormatField();
        checkFuncionario_Ativo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        InputPesquisa_Funcionario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        botaoFuncionario_Pesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Funcionários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        InputFuncionario_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_NomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome :");

        InputFuncionario_Cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_CpfActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF :");

        InputFuncionario_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_TelefoneActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cargo");

        InputFuncionario_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_CargoActionPerformed(evt);
            }
        });

        jLabel9.setText("Cargo :");

        jLabel10.setText("Salário :");

        InputFuncionario_Data.setEditable(false);
        InputFuncionario_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_DataActionPerformed(evt);
            }
        });

        jLabel11.setText("Data");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Sistema");

        InputFuncionario_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_UsuarioActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Usuário :");

        InputFuncionario_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_SenhaActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Senha :");

        botaoFuncionario_Limpar.setText("Limpar");

        botaoFuncionario_Salvar.setText("Salvar");

        InputFuncionario_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFuncionario_CodigoActionPerformed(evt);
            }
        });

        InputFuncionario_Salario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        checkFuncionario_Ativo.setText("Ativo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputFuncionario_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputFuncionario_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputFuncionario_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(InputFuncionario_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botaoFuncionario_Limpar)
                                        .addGap(249, 249, 249)
                                        .addComponent(botaoFuncionario_Salvar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(InputFuncionario_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(InputFuncionario_Salario, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                        .addComponent(InputFuncionario_Data, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(checkFuncionario_Ativo)
                                            .addGap(277, 277, 277))
                                        .addComponent(InputFuncionario_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(InputFuncionario_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(InputFuncionario_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFuncionario_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFuncionario_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFuncionario_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFuncionario_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(InputFuncionario_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFuncionario_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFuncionario_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFuncionario_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(checkFuncionario_Ativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFuncionario_Limpar)
                    .addComponent(botaoFuncionario_Salvar))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        InputPesquisa_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPesquisa_FuncionarioActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Nome / CPF :");

        botaoFuncionario_Pesquisar.setText("Pesquisar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(36, 36, 36)
                        .addComponent(InputPesquisa_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoFuncionario_Pesquisar)
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPesquisa_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(botaoFuncionario_Pesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InputFuncionario_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_NomeActionPerformed

    private void InputFuncionario_CpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_CpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_CpfActionPerformed

    private void InputFuncionario_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_TelefoneActionPerformed

    private void InputFuncionario_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_CargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_CargoActionPerformed

    private void InputFuncionario_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_DataActionPerformed

    private void InputFuncionario_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_UsuarioActionPerformed

    private void InputFuncionario_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_SenhaActionPerformed

    private void InputPesquisa_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPesquisa_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPesquisa_FuncionarioActionPerformed

    private void InputFuncionario_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFuncionario_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFuncionario_CodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputFuncionario_Cargo;
    private javax.swing.JTextField InputFuncionario_Codigo;
    private javax.swing.JTextField InputFuncionario_Cpf;
    private javax.swing.JTextField InputFuncionario_Data;
    private javax.swing.JTextField InputFuncionario_Nome;
    private view.JNumberFormatField InputFuncionario_Salario;
    private javax.swing.JTextField InputFuncionario_Senha;
    private javax.swing.JTextField InputFuncionario_Telefone;
    private javax.swing.JTextField InputFuncionario_Usuario;
    private javax.swing.JTextField InputPesquisa_Funcionario;
    private javax.swing.JButton botaoFuncionario_Limpar;
    private javax.swing.JButton botaoFuncionario_Pesquisar;
    private javax.swing.JButton botaoFuncionario_Salvar;
    private javax.swing.JCheckBox checkFuncionario_Ativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
