/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GerenciarMesa;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author marqu
 */
public class NovoPedido extends javax.swing.JFrame {

    /**
     * Creates new form NovoPedido
     */
    public NovoPedido() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        
        ActionListener actionListener = new GerenciarMesa(this);
        addMesa.addActionListener(actionListener);
    }

    public JLabel getMensagem() {
        return mensagem;
    }
    
    public JTextField getStatus_mesa() {
        return status_mesa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status_mesa = new javax.swing.JTextField();
        addMesa = new javax.swing.JButton();
        mensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Pedidos = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenu();
        Reservas = new javax.swing.JMenu();
        Administracao = new javax.swing.JMenu();
        Funcionarios = new javax.swing.JMenuItem();
        Estoque = new javax.swing.JMenuItem();
        Cardapio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMesa.setText("Inserir Mesa");

        mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagem.setToolTipText("");

        jLabel1.setText("Status da Mesa:");

        Pedidos.setText("Pedidos");
        jMenuBar1.add(Pedidos);

        Cliente.setText("Cliente");
        jMenuBar1.add(Cliente);

        Reservas.setText("Reservas");
        jMenuBar1.add(Reservas);

        Administracao.setText("Administração");

        Funcionarios.setText("Funcionários");
        Administracao.add(Funcionarios);

        Estoque.setText("Estoque");
        Administracao.add(Estoque);

        Cardapio.setText("Cardapio");
        Cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardapioActionPerformed(evt);
            }
        });
        Administracao.add(Cardapio);

        jMenuBar1.add(Administracao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(status_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(addMesa)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensagem)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addMesa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(status_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardapioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardapioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administracao;
    private javax.swing.JMenuItem Cardapio;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenuItem Estoque;
    private javax.swing.JMenuItem Funcionarios;
    private javax.swing.JMenu Pedidos;
    private javax.swing.JMenu Reservas;
    private javax.swing.JButton addMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel mensagem;
    private javax.swing.JTextField status_mesa;
    // End of variables declaration//GEN-END:variables

}
