/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author marqu
 */
public class NovoPedido extends javax.swing.JFrame {

    /**
     * Creates new form NovoPedido
     */
    public NovoPedido() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Pedidos = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenu();
        Reservas = new javax.swing.JMenu();
        Administracao = new javax.swing.JMenu();
        Funcionarios = new javax.swing.JMenuItem();
        Estoque = new javax.swing.JMenuItem();
        Cardapio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pedidos.setText("Pedidos");
        jMenuBar1.add(Pedidos);

        Cliente.setText("Cliente");
        jMenuBar1.add(Cliente);

        Reservas.setText("Reservas");
        jMenuBar1.add(Reservas);

        Administracao.setText("Administração");

        Funcionarios.setText("Funcionários");
        Administracao.add(Funcionarios);

        Estoque.setText("Estoque");
        Administracao.add(Estoque);

        Cardapio.setText("Cardapio");
        Cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardapioActionPerformed(evt);
            }
        });
        Administracao.add(Cardapio);

        jMenuBar1.add(Administracao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardapioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardapioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administracao;
    private javax.swing.JMenuItem Cardapio;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenuItem Estoque;
    private javax.swing.JMenuItem Funcionarios;
    private javax.swing.JMenu Pedidos;
    private javax.swing.JMenu Reservas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
