/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GerenciarPedidos;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;




/**
 *
 * @author marqu
 */
public class RestauranteView extends javax.swing.JFrame {
    GerenciarPedidos PedidosListener;
    private static final DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
    /**
     * Creates new form NovoPedido
     */
    public RestauranteView() {
        
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // added
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // added
        this.setVisible(true);
        //this.setExtendedState(this.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);        

        jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override protected int calculateTabHeight(
                int tabPlacement, int tabIndex, int fontHeight) {
                return 32;
            }

            @Override protected void paintTab(
                Graphics g, int tabPlacement, Rectangle[] rects, int tabIndex,
                Rectangle iconRect, Rectangle textRect) {
     
                super.paintTab(g, tabPlacement, rects, tabIndex, iconRect, textRect);
            }
        });  
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pedidoView = new view.PedidoView();
        clienteView = new view.ClienteView();
        funcionarioView1 = new view.FuncionarioView();
        estoqueView1 = new view.EstoqueView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPane1.addTab("Pedidos", pedidoView);
        jTabbedPane1.addTab("Clientes", clienteView);
        jTabbedPane1.addTab("Funcionários", funcionarioView1);
        jTabbedPane1.addTab("Estoque", estoqueView1);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.ClienteView clienteView;
    private view.EstoqueView estoqueView1;
    private view.FuncionarioView funcionarioView1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private view.PedidoView pedidoView;
    // End of variables declaration//GEN-END:variables

}
