/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GerenciarPedidos;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.MaskFormatter;




/**
 *
 * @author marqu
 */
public class RestauranteView extends javax.swing.JFrame {
    GerenciarPedidos PedidosListener;
    private static final DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
    /**
     * Creates new form NovoPedido
     */
    public RestauranteView() {
       
        
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // added
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // added
        this.setVisible(true);
        //this.setExtendedState(this.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        
        PedidosListener = new GerenciarPedidos(this); 
        botaoPedido_Finalizar.addActionListener(PedidosListener);
        botaoPedido_Limpar.addActionListener(PedidosListener);
        botaoPedido_Salvar.addActionListener(PedidosListener);
        botaoPedido_Pesquisar.addActionListener(PedidosListener);
        metodoPesquisaPedido.addActionListener(PedidosListener);
        InputPesquisa_Pedido.addActionListener(PedidosListener);

        jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override protected int calculateTabHeight(
                int tabPlacement, int tabIndex, int fontHeight) {
                return 32;
            }

            @Override protected void paintTab(
                Graphics g, int tabPlacement, Rectangle[] rects, int tabIndex,
                Rectangle iconRect, Rectangle textRect) {
     
                super.paintTab(g, tabPlacement, rects, tabIndex, iconRect, textRect);
            }
        });
        
        TabelaPedido_Pesquisa.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                
                if (me.getClickCount() >= 2 && row!= -1) {
                    String nome = TabelaPedido_Pesquisa.getColumnName(2);
                    if( "CPF".equals(nome)){
                       PedidosListener.setCliente_values(row);
                    }else if("Preço".equals(nome)){
                       PedidosListener.setProdutosOnTable(row);
                    }else{
                        
                    }
                }
            }
        });
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );

        TabelaPedido_Produtos.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );

        
        
       
        
    }

    public JTextField getInputPedido_Cliente() {
        return InputPedido_Cliente;
    }

    public JFormattedTextField getInputPedido_Data() {
        return InputPedido_Data;
    }

    public JFormattedTextField getInputPedido_Desconto() {
        return InputPedido_Desconto;
    }

    public JTextField getInputPedido_Mesa() {
        return InputPedido_Mesa;
    }

    public JFormattedTextField getInputPedido_Pago() {
        return InputPedido_Pago;
    }

    public JTextField getInputPedido_Preço() {
        return InputPedido_Preço;
    }

    public JFormattedTextField getInputPedido_Troco() {
        return InputPedido_Troco;
    }

    public JTextField getInputPesquisa_Pedido() {
        return InputPesquisa_Pedido;
    }

    public CustomJTable getTabelaPedido_Pesquisa() {
        return TabelaPedido_Pesquisa;
    }

    public JTable getTabelaPedido_Produtos() {
        return TabelaPedido_Produtos;
    }

    public JLabel getLabelPedido_MetodoPesquisa() {
        return labelPedido_MetodoPesquisa;
    }

    public JComboBox getMetodoPesquisaPedido() {
        return metodoPesquisaPedido;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPedido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InputPedido_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InputPedido_Mesa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPedido_Produtos = new javax.swing.JTable();
        InputPedido_Data = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        metodoPesquisaPedido = new javax.swing.JComboBox();
        labelPedido_MetodoPesquisa = new javax.swing.JLabel();
        InputPesquisa_Pedido = new javax.swing.JTextField();
        botaoPedido_Pesquisar = new javax.swing.JButton();
        JScrollPane3 = new javax.swing.JScrollPane();
        TabelaPedido_Pesquisa = new view.CustomJTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InputPedido_Preço = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        radioPedido_PagamentoCartao = new javax.swing.JRadioButton();
        radioPedido_PagamentoDinheiro = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        botaoPedido_Limpar = new javax.swing.JButton();
        botaoPedido_Salvar = new javax.swing.JButton();
        botaoPedido_Finalizar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        InputPedido_Desconto = new javax.swing.JFormattedTextField();
        InputPedido_Troco = new javax.swing.JFormattedTextField();
        InputPedido_Pago = new javax.swing.JFormattedTextField();
        jPanelCliente = new javax.swing.JPanel();
        jPanelReservas = new javax.swing.JPanel();
        addMesa = new javax.swing.JButton();
        status_mesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();
        jPanelFuncionarios = new javax.swing.JPanel();
        jPanelEstoque = new javax.swing.JPanel();
        jPanelCardapio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mesa:");

        InputPedido_Mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPedido_MesaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Produtos:");

        TabelaPedido_Produtos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TabelaPedido_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelaPedido_Produtos.setRowHeight(30);
        jScrollPane1.setViewportView(TabelaPedido_Produtos);

        InputPedido_Data.setEditable(false);
        try {
            InputPedido_Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        InputPedido_Data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPedido_Data.setToolTipText("");
        InputPedido_Data.setFocusable(false);
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        InputPedido_Data.setText(dateFormat.format(date));
        InputPedido_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPedido_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputPedido_Cliente)
                            .addComponent(InputPedido_Mesa)
                            .addComponent(InputPedido_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputPedido_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPedido_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(InputPedido_Mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Pesquisar por:");

        metodoPesquisaPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        metodoPesquisaPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Produtos", "Pedidos Pendentes" }));

        labelPedido_MetodoPesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPedido_MetodoPesquisa.setText("Cliente:");

        InputPesquisa_Pedido.setToolTipText("");
        InputPesquisa_Pedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputPesquisa_PedidoKeyReleased(evt);
            }
        });

        botaoPedido_Pesquisar.setText("Pesquisar");

        JScrollPane3.setViewportView(TabelaPedido_Pesquisa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metodoPesquisaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelPedido_MetodoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(InputPesquisa_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(botaoPedido_Pesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metodoPesquisaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPedido_MetodoPesquisa)
                    .addComponent(InputPesquisa_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPedido_Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Desconto:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Preço Total:");

        InputPedido_Preço.setEditable(false);
        InputPedido_Preço.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPedido_Preço.setText("0.00");
        InputPedido_Preço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPedido_PreçoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Pagamento:");

        radioPedido_PagamentoCartao.setText("Cartão");
        radioPedido_PagamentoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPedido_PagamentoCartaoActionPerformed(evt);
            }
        });

        radioPedido_PagamentoDinheiro.setSelected(true);
        radioPedido_PagamentoDinheiro.setText("Dinheiro");
        radioPedido_PagamentoDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPedido_PagamentoDinheiroActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pago:");

        botaoPedido_Limpar.setText("Limpar");

        botaoPedido_Salvar.setText("Salvar");

        botaoPedido_Finalizar.setText("Finalizar");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Troco:");

        InputPedido_Desconto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPedido_Desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPedido_DescontoActionPerformed(evt);
            }
        });

        InputPedido_Troco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPedido_Troco.setText("0.00");
        InputPedido_Troco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPedido_TrocoActionPerformed(evt);
            }
        });

        InputPedido_Pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputPedido_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputPedido_Preço)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(radioPedido_PagamentoCartao)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioPedido_PagamentoDinheiro))
                                    .addComponent(InputPedido_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(InputPedido_Troco, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoPedido_Limpar)
                        .addGap(81, 81, 81)
                        .addComponent(botaoPedido_Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoPedido_Finalizar)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(InputPedido_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(InputPedido_Preço, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(radioPedido_PagamentoCartao)
                    .addComponent(radioPedido_PagamentoDinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(InputPedido_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(InputPedido_Troco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPedido_Limpar)
                    .addComponent(botaoPedido_Finalizar)
                    .addComponent(botaoPedido_Salvar)))
        );

        javax.swing.GroupLayout jPanelPedidoLayout = new javax.swing.GroupLayout(jPanelPedido);
        jPanelPedido.setLayout(jPanelPedidoLayout);
        jPanelPedidoLayout.setHorizontalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelPedidoLayout.setVerticalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pedidos", jPanelPedido);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1207, Short.MAX_VALUE)
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cliente", jPanelCliente);

        addMesa.setText("Inserir Mesa");

        jLabel1.setText("Status da Mesa:");

        mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelReservasLayout = new javax.swing.GroupLayout(jPanelReservas);
        jPanelReservas.setLayout(jPanelReservasLayout);
        jPanelReservasLayout.setHorizontalGroup(
            jPanelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservasLayout.createSequentialGroup()
                .addGroup(jPanelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReservasLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelReservasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status_mesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelReservasLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(252, 252, 252)))
                        .addGap(88, 88, 88)
                        .addComponent(addMesa)))
                .addGap(0, 637, Short.MAX_VALUE))
        );
        jPanelReservasLayout.setVerticalGroup(
            jPanelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReservasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mensagem)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMesa))
                .addContainerGap(585, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservas", jPanelReservas);

        javax.swing.GroupLayout jPanelFuncionariosLayout = new javax.swing.GroupLayout(jPanelFuncionarios);
        jPanelFuncionarios.setLayout(jPanelFuncionariosLayout);
        jPanelFuncionariosLayout.setHorizontalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1207, Short.MAX_VALUE)
        );
        jPanelFuncionariosLayout.setVerticalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Funcionários", jPanelFuncionarios);

        javax.swing.GroupLayout jPanelEstoqueLayout = new javax.swing.GroupLayout(jPanelEstoque);
        jPanelEstoque.setLayout(jPanelEstoqueLayout);
        jPanelEstoqueLayout.setHorizontalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1207, Short.MAX_VALUE)
        );
        jPanelEstoqueLayout.setVerticalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Estoque", jPanelEstoque);

        javax.swing.GroupLayout jPanelCardapioLayout = new javax.swing.GroupLayout(jPanelCardapio);
        jPanelCardapio.setLayout(jPanelCardapioLayout);
        jPanelCardapioLayout.setHorizontalGroup(
            jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1207, Short.MAX_VALUE)
        );
        jPanelCardapioLayout.setVerticalGroup(
            jPanelCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cardápio", jPanelCardapio);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputPesquisa_PedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPesquisa_PedidoKeyReleased
        int index = metodoPesquisaPedido.getSelectedIndex();
        if(index==0){
            PedidosListener.lista_clientes();
        }else if(index==1){
            PedidosListener.lista_menu();
        }else{
            // Lista pedidos
        }    
          
    }//GEN-LAST:event_InputPesquisa_PedidoKeyReleased

    private void radioPedido_PagamentoDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPedido_PagamentoDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPedido_PagamentoDinheiroActionPerformed

    private void radioPedido_PagamentoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPedido_PagamentoCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPedido_PagamentoCartaoActionPerformed

    private void InputPedido_MesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPedido_MesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPedido_MesaActionPerformed

    private void InputPedido_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPedido_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPedido_DataActionPerformed

    private void InputPedido_PreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPedido_PreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPedido_PreçoActionPerformed

    private void InputPedido_DescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPedido_DescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPedido_DescontoActionPerformed

    private void InputPedido_TrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPedido_TrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPedido_TrocoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputPedido_Cliente;
    private javax.swing.JFormattedTextField InputPedido_Data;
    private javax.swing.JFormattedTextField InputPedido_Desconto;
    private javax.swing.JTextField InputPedido_Mesa;
    private javax.swing.JFormattedTextField InputPedido_Pago;
    private javax.swing.JTextField InputPedido_Preço;
    private javax.swing.JFormattedTextField InputPedido_Troco;
    private javax.swing.JTextField InputPesquisa_Pedido;
    private javax.swing.JScrollPane JScrollPane3;
    private view.CustomJTable TabelaPedido_Pesquisa;
    private javax.swing.JTable TabelaPedido_Produtos;
    private javax.swing.JButton addMesa;
    private javax.swing.JButton botaoPedido_Finalizar;
    private javax.swing.JButton botaoPedido_Limpar;
    private javax.swing.JButton botaoPedido_Pesquisar;
    private javax.swing.JButton botaoPedido_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCardapio;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelEstoque;
    private javax.swing.JPanel jPanelFuncionarios;
    private javax.swing.JPanel jPanelPedido;
    private javax.swing.JPanel jPanelReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelPedido_MetodoPesquisa;
    private javax.swing.JLabel mensagem;
    private javax.swing.JComboBox metodoPesquisaPedido;
    private javax.swing.JRadioButton radioPedido_PagamentoCartao;
    private javax.swing.JRadioButton radioPedido_PagamentoDinheiro;
    private javax.swing.JTextField status_mesa;
    // End of variables declaration//GEN-END:variables

}
